### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by KraXen72** [pilcrowOnPaper/niagara#7]
hi, i have ideas for several improvements. i'd be down to implement them myself + pr them, just want to know if you agree with them
- stopwatch mode:
    - instead of counting down, there would be another mode where the app counts up. this could be a small toggle in nav + hotkey
- action buttons to play/pause the timer, edit the timer, and reset the stopwatch (also new hotkey).
    - (icons, only show relevant at times => edit is hidden when stopwatch is running, etc)
- internal cleanup of format parsing
    - attempt to make the parsing of input more readable (same functionality)
  
 please let me know your thoughts on each of these. i am aware i could just fork it etc but tbh i'd rather contribute & the url niagara.vercel.app is clean and nice

**Comment by pilcrowonpaper** [comment]
Yeah, I don't have much time right now and my priority is in other projects. Sorry!

I could just give you the url, would that work for you?

**Comment by KraXen72** [comment]
that would be fine too, but if you don't mind, i'll contribute to this project. you're the one who made the initial app & idea, i'm just adding improvement. 

but if you want to archive/deprecate this repo, the url would be also satisfactory.
thanks!

**Comment by pilcrowonpaper** [comment]
You seem to be much more interested in the project so I think it's better if it's under your control.

I'll transfer the repo to you, so can you rename the existing `KraXen72/niagara` repo?

**Comment by KraXen72** [comment]
!! okay thanks a lot. i'll rename my fork

**Comment by pilcrowonpaper** [comment]
@KraXen72 
It seems you have to delete the fork... my bad
<img width="788" alt="Screenshot 2022-12-26 at 23 44 37" src="https://user-images.githubusercontent.com/80624252/209560137-5a38b5d9-7b47-44e4-a444-45c7fef16f5e.png">

**Comment by KraXen72** [comment]
done

**Comment by pilcrowonpaper** [comment]
Done, make sure to deploy it with the appropriate url. I've deleted the url, so be quick!

**Comment by KraXen72** [comment]
uhh how 2 deploy. im not sure if i have to accept the repo ownership or something first? like what do i need to deploy to the url

**Comment by pilcrowonpaper** [comment]
Uhhhh ok
1. Accept the repo ownership
2. Create an account with vercel using Github
3. Connect the repo
4. Deploy with the default config
5. Change domain after deployment is complete (may not be necessary)

**Comment by KraXen72** [comment]
![image](https://user-images.githubusercontent.com/21956756/209562131-6b9d6bdb-f07c-4b76-b02a-1f057673c718.png)

**Comment by pilcrowonpaper** [comment]
Ahhh sorry, I re-claimed the domain when it didn't let me transfer the repo. Released the domain again, should be fine now.

**Comment by KraXen72** [comment]
okay it works now. thanks a lot for everything so far!
